backend:
  name: git-gateway
  branch: master
media_folder: public/images
public_folder: /images
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts/"
    extension: "mdx"
    format: "frontmatter"
    create: true
    summary: "{{excerpt}}"
    fields:
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "datetime"
        format: "Month D, Yr"
        dateFormat: "Month D, Yr"
        timeFormat: false
      - label: "Description"
        name: "excerpt"
        widget: "string"
      - label: "Featured Image"
        name: "thumbnail"
        widget: "image"
        choose_url: true
        default: "/images/img1.jpg"
        media_library:
          config:
            multiple: true