backend:
  name: git-gateway
  branch: master
media_folder: public/images/posts
public_folder: /images/posts
publish_mode: editorial_workflow

collections:
  - name: "posts"
    label: "Posts"
    folder: "posts/"
    extension: "md"
    format: "frontmatter"
    create: true
    slug: "{{slug}}"
    identifier_field: slug
    summary: "{{excerpt}}"
    fields:
      - label: "Slug"
        name: "slug"
        widget: "string"
      - label: "Title"
        name: "title"
        widget: "string"
      - label: "Publish Date"
        name: "date"
        widget: "date"
        format: "MMM DD, YYYY"
      - label: "Description"
        name: "excerpt"
        widget: "string"
      - label: "Featured Image"
        name: "cover_image"
        widget: "image"
        choose_url: true
        media_library:
          config:
            multiple: true
      - label: "Body"
        name: "body"
        widget: "markdown"